//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMSAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FacultyManagementSystemEntities : DbContext
    {
        public FacultyManagementSystemEntities()
            : base("name=FacultyManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Course> Tbl_Course { get; set; }
        public virtual DbSet<Tbl_Department> Tbl_Department { get; set; }
        public virtual DbSet<Tbl_Faculty> Tbl_Faculty { get; set; }
        public virtual DbSet<tbl_Role> tbl_Role { get; set; }
        public virtual DbSet<Tbl_RoleMapping> Tbl_RoleMapping { get; set; }
        public virtual DbSet<tbl_UserLogin> tbl_UserLogin { get; set; }
    
        public virtual ObjectResult<GetDepartment_Result> GetDepartment()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDepartment_Result>("GetDepartment");
        }
    }
}
