//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMSAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Department
    {
        public int Dept_ID { get; set; }
        public string Dept_Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public string createdBy { get; set; }
        public string UpdatedBy { get; set; }
    }
}
