//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMSAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BookPublish
    {
        public int PublishID { get; set; }
        public string BookName { get; set; }
        public Nullable<System.DateTime> Publish_Date { get; set; }
        public Nullable<int> FacultyID { get; set; }
    }
}
